theme: jekyll-theme-minimal
title: Biomedical Informatics and Data Science Student Group
description: BIDS Student Group is a community of graduate students working in fields of research surrounding biomedical and clinical informatics at Northwestern University.
